### ISSUE TITLE
The built-in llvm compiler 17 of vs2022 cannot compile

### ISSUE THREAD

**Issue by icyfox168168** [boost-ext/reflect#28]

**Comment by icyfox168168** [comment]
1>./reflect.h(261,23): error : static assertion failed due to requirement 'std::basic_string_view<char, std::char_traits<char>>{"int"} == type_name<int>()'
1>./reflect.h(273,23): error : static assertion failed due to requirement 'std::basic_string_view<char, std::char_traits<char>>{"int"} == type_name(int{})'
1>./reflect.h(711,45): error : expected unqualified-id

**Comment by icyfox168168** [comment]
1>./reflect.h(758,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(760,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(762,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(710,37): error : no matching function for call to 'offset_of'
1>./reflect.h(763,23): message : in instantiation of function template specialization 'reflect::offset_of<2ULL, s>' requested here
1>./reflect.h(705,34): message : candidate template ignored: substitution failure [with N = 1, T = s]
1>./reflect.h(763,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(710,37): error : no matching function for call to 'offset_of'
1>./reflect.h(764,23): message : in instantiation of function template specialization 'reflect::offset_of<3ULL, s>' requested here
1>./reflect.h(705,34): message : candidate template ignored: substitution failure [with N = 2, T = s]
1>./reflect.h(764,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(766,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(710,37): error : no matching function for call to 'offset_of'
1>./reflect.h(767,23): message : in instantiation of function template specialization 'reflect::offset_of<2ULL, s2>' requested here
1>./reflect.h(705,34): message : candidate template ignored: substitution failure [with N = 1, T = s2]
1>./reflect.h(767,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(710,37): error : no matching function for call to 'offset_of'
1>./reflect.h(768,23): message : in instantiation of function template specialization 'reflect::offset_of<3ULL, s2>' requested here
1>./reflect.h(705,34): message : candidate template ignored: substitution failure [with N = 2, T = s2]
1>./reflect.h(768,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(710,37): error : no matching function for call to 'offset_of'
1>./reflect.h(769,23): message : in instantiation of function template specialization 'reflect::offset_of<4ULL, s2>' requested here
1>./reflect.h(705,34): message : candidate template ignored: substitution failure [with N = 3, T = s2]
1>./reflect.h(769,23): error : static assertion expression is not an integral constant expression
1>./reflect.h(710,37): error : no matching function for call to 'offset_of'
1>./reflect.h(770,23): message : in instantiation of function template specialization 'reflect::offset_of<5ULL, s2>' requested here
1>./reflect.h(705,34): message : candidate template ignored: substitution failure [with N = 4, T = s2]
1>./reflect.h(770,23): error : static assertion expression is not an integral constant expression
1>fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by krzysztof-jusiak** [comment]
What compiler exactly is it? clang-17 is being tested - https://godbolt.org/z/xPc19Moef, same as msvc-19.3+. Is that clang-cl? Would it be possible to provide godbolt link to reproduce it?

**Comment by icyfox168168** [comment]
I still cannot use the latest version of VS2022 19.1, and I have set it to support the latest version of the C++standard

**Comment by krzysztof-jusiak** [comment]
I did try to make it work on versions before msvc-19.36 (https://godbolt.org/z/nq5jx1GYK) but, unfortunately, I wasn't able to. MSVC before 19.36 is just missing features and it would require a lot workarounds/ifdefs to make it work, which I wanna avoid. Hope, you will be able to upgrade at some point to versions which are supported. The bar won't get higher than msvc-19.36. Also, going to improve the error message though when required features aren't in-place. Thanks.
